IO_OPTION:
  INPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/datasets'
  OUTPUT_ROOT: '/media/hiroki/HDD1TB/research/dcase2021_task2/output/sliding_window_32'
  
mel_spectrogram_param:
  n_mels: 128
  frames : 64
  n_fft: 1024
  hop_length: 512
  power: 2.0

fit:
  batch_size : 16
  shuffle : True
  num_epochs : 100
  devise : 'cuda'

etc:
  test_size : 0.3
  max_fpr : 0.1
